#!/bin/sh
set -e
# This script can be called in the following ways:
#
# After the package was installed:
#       <postinst> configure <old-version>
#
#
# If prerm fails during upgrade or fails on failed upgrade:
#       <old-postinst> abort-upgrade <new-version>
#
# If prerm fails during deconfiguration of a package:
#       <postinst> abort-deconfigure in-favour <new-package> <version>
#                  removing <old-package> <version>
#
# If prerm fails during replacement due to conflict:
#       <postinst> abort-remove in-favour <new-package> <version>


case "$1" in
    configure)
	update-alternatives \
		--install /usr/share/plymouth/themes/default.plymouth default.plymouth \
		/usr/share/plymouth/themes/ubuntukylin-logo/ubuntukylin-logo.plymouth 150

	update-alternatives \
		--install /usr/share/plymouth/themes/text.plymouth text.plymouth \
		/usr/share/plymouth/themes/ubuntukylin-text/ubuntukylin-text.plymouth 150

	if [ -e /boot/grub/grub.cfg ]; then
		# Will break Live CD generation, LP #1228462
		update-grub || true
	fi

	if which update-initramfs >/dev/null 2>&1
	then
	    update-initramfs -u
	fi
	;;

    abort-upgrade|abort-deconfigure|abort-remove)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

# Automatically added by dh_icons/11.1.6ubuntu2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/ukui-icon-theme /usr/share/icons/ukui-icon-theme-one
	fi
fi
# End automatically added section

